### ISSUE TITLE
interceptLinkClick interferes with amp-analytics click tracking

### ISSUE THREAD

**Issue by cvializ** [google/amp-pwa-demo#26]
If you check out my branch https://github.com/cvializ/amp-pwa-demo/tree/click-bug and click on a link, you'll notice that the request to example.com does not occur after the user clicks a link. If you comment out `e.preventDefault` in `interceptLinkClick`, the analytics request does occur.

This bug was encountered while troubleshooting https://github.com/ampproject/amphtml/issues/11540 where the reporter appears to have used this demo as a starting point.

**Comment by danielrozenberg** [comment]
I can't reproduce this. Seems like this is fixed?

**Comment by cvializ** [comment]
Same I will close for now.
